### ISSUE TITLE
Curl exists with errorcode 1. 

### ISSUE THREAD

**Issue by halllo2** [hschneider/neutralino-curl#2]
I've downloaded the code, copied the windows bin file to the correct location. And i've run: neu update and neu run. 
When pressing the download button. It shows "Curl finished with exit code 1". The url is correct.

**Comment by hschneider** [comment]
Exit code 1 means unsupported protocol. 
Please check the URL.

Have copied all files from _install/windows/bin ?
Have placed the bin folder **beside** the resources folder?
What happens, when you cd to the bin folder and execute curl from the windows terminal ?

**Comment by halllo2** [comment]
URL is https://marketmix.com/git-assets/neutralino-curl/test.jpg
Also, i've changed no code in one of the html/js files. 

folder layout: 
```
LICENSE
neutralino.config.json
README.md
.tmp\auth_info.json
bin\curl-ca-bundle.crt
bin\curl.exe
bin\libcurl-x64.def
bin\libcurl-x64.dll
bin\neutralino-linux_arm64
bin\neutralino-linux_armhf
bin\neutralino-linux_x64
bin\neutralino-mac_arm64
bin\neutralino-mac_universal
bin\neutralino-mac_x64
bin\neutralino-win_x64.exe
resources\index.html
resources\styles.css
resources\bin\curl-ca-bundle.crt
resources\bin\curl.exe
resources\bin\libcurl-x64.def
resources\bin\libcurl-x64.dll
resources\icons\appIcon.png
resources\icons\logo.gif
resources\icons\trayIcon.png
resources\js\main.js
resources\js\neutralino.d.ts
resources\js\neutralino.js
resources\js\neutralino-curl\curl.js
```

In (both) the bin-folders, curl works as intended. So using ".\curl <url> -o file.txt" prints the output correct to the file.

**Comment by hschneider** [comment]
Thanks for your post. 
There was indeed an issue with the path under Windows. This should be fixed in v1.0.8. 
Please test.

# Changes:

This build comes with some breaking changes. The bin folder has been moved to `/extension/curl/bin` to eliminate a path issue under Windows:

## Setup on all Platforms
- Copy the content from `_install/YOUR_PLATFORM/bin/`to `extensions/curl/bin/`.
- Include `resources/neutralino-curl/curl.js`in your `index.hml`file.
- Init CURL and add the required events to `main.js`.

## Deployment

### On Windows and Linux

The `extensions` folder needs to be placed beside your `resources..neu` folder:

```
app.exe
resources.neu
extensions
```
### On macOS
The `extensions` folder goes into your app bundle's `Resources` folder. This can be automated with **[[Neutralino Build Scripts.](https://github.com/hschneider/neutralino-build-scripts)]**

**Comment by halllo2** [comment]
It works now only when the application is build. 
But the real problem is that Windows uses backslashes, and it gives an error, when using normal slashes in the commandline. 

So i've changed line 18 and 122 of curl.js. With that change, the program works. 
18: this.appResourcesEXT = NL_PATH + '\\extensions';   // App BIN resources
122: let cmd = await Neutralino.os.spawnProcess(this.appResourcesEXT + `\\curl\\bin\\curl ${args}`);

**Comment by hschneider** [comment]
Thanks for testing.

The slashes are transformed by the underlying Neutralino code, so that's not the issue.
The problem was an inconsistent behavior of NL_PATH. While NL_PATH+"/extensions" point to the right path on other platforms, it requires NL_CWD+"/extensions" under Windows.

Please test again with 1.1.9.

**Comment by halllo2** [comment]
It works, thanks for your time.

**Comment by hschneider** [comment]
Welcome - thanks for YOUR time :-)
